unique_ids:
  forms:
    homepage.login: '1724165234325124737717878.00758'
    homepage.logo.PasswordResetDialog: KJCAOP5OD7DQKTZDZDWKVNYTSLQIZUKH
    homepage.mainmenu: '1723995158959267520776202.30795'
    homepage.logo: JC27TP3SO2JKJZIQPAEK65IQXXS2NPGY
    homepage.signup: ZXGZJUBP4YAJ4XATU6FJDW5QLJT4KFJR
    homepage.autor: '1723996414427547758879446.4159'
    homepage: '172399507020314322151835.756802'
    homepage.termsuse: 7F2INMKNYVCDRH4WF2XULR5XJ5RD7X7O
    homepage.privacenotice: ALOMTEE3UJXNUVQTWBDWCI4MA2LSHMJL
    homepage.termservice: T5TESYAUKBFPROJMQUBEE2632OX7BJE2
    homepage.forgotPass: E674TPFO52L2CKSHKUBAURCOVHCXOD5Q
  modules:
    homepage.logo.Globals: WLQ3L57XGGVWMD4KEBASWS7YFMLIEUYE
    homepage.hpGlobals: ON4XFG3UKGA2LBC2VIM6MELVBIFYIP5L
  server_modules:
    ServerModule1: '1724182604405133134129118.8859'
    jDoc: '1724183397337473908664175.3725'
  assets:
    dashboard.html: 7B4PCZH2UUGMD5FIHQSX4GO5ENMMU55Z
    single-column.html: CJOPWVX3AVXKHJ7ZWDX57PCCA6GP5VVO
    theme.css: ZXDSYBW4555BLBTAW5SK2AT2OZWGFQVR
  scripts: {}
