unique_ids:
  forms: {}
  modules: {}
  server_modules: {}
  assets:
    single-column.html: CJOPWVX3AVXKHJ7ZWDX57PCCA6GP5VVO
    dashboard.html: 7B4PCZH2UUGMD5FIHQSX4GO5ENMMU55Z
    theme.css: ZXDSYBW4555BLBTAW5SK2AT2OZWGFQVR
  scripts: {}
