unique_ids:
  assets:
    dashboard.html: 7B4PCZH2UUGMD5FIHQSX4GO5ENMMU55Z
    single-column.html: CJOPWVX3AVXKHJ7ZWDX57PCCA6GP5VVO
    theme.css: ZXDSYBW4555BLBTAW5SK2AT2OZWGFQVR
  forms:
    homepage: '172399507020314322151835.756802'
    homepage.Empleado: Z5VTK2LDLRESHDTB4FK5L34CONEFFAQ5
    homepage.Empleados: 53ZW65R2K2Y4TSCCUUQZMJSBSYSDGXNR
    homepage.Empleados.RowTemplate1: 2T72GC5ET5YKQ5PFR2XRA3US7GIJU3BV
    homepage.autor: '1723996414427547758879446.4159'
    homepage.claseexp: KWKKGDXFWKTRTTITNQPJOD7UUV7D7AHN
    homepage.clasesexp: VO2FFPTHIQYS54QP2PHUX4SHBC6C3XL7
    homepage.clasesexp.RowTemplate8: 45WTRMXEYP24HSS2RLSB36MGCJGRVGLR
    homepage.expediente: CHJ66Y7BPKKD233RK3E2Z75LREIEPLUL
    homepage.expedientes: YGNLIA2RI6P2CI6OVWYZOGO6YMHFGHTF
    homepage.expedientes.RowTemplate9: RFPJYUZXCAFBB3H36UFVGED2XL2HOYYG
    homepage.forgotPass: WAGOL2RZDSN2KBN7VKYRHAY5MUFTGJC3
    homepage.jdocTransfer: 5JIF6YFNPZBB2WBILO4HWTUHW76QSJI7
    homepage.jdocTransfer_copy: CA422K32OLOLCQDSVA24OMKVFQMYDZCH
    homepage.login: '1724165234325124737717878.00758'
    homepage.logo: B4HVCBUMZHOW6T6HFERMJD42AQ3QJTGP
    homepage.logo.PasswordResetDialog: 524HY3Z5IFBBHGTMUDF54KTJDKNF2VDP
    homepage.mainmenu: '1723995158959267520776202.30795'
    homepage.sucursal: VLUMS3SAOYQCWKUXMXEYJHWJ3N4C3TIU
    homepage.sucursales: S55XBLN4TZFJYJ2AR6ANJ3T4H7NDV5XG
    homepage.sucursales.RowTemplate7: SI74BALIVHC6NVQOEBETLW25T3QIZIGE
  modules:
    homepage.hpGlobals: F5KICQ4EMZLO44NHQBXV4ROK37NKUGM3
    homepage.logo.Globals: DPKXL4EDHOIS65NRD4DBR433HIEC6PIS
  scripts: {}
  server_modules:
    ServerModule1: '1724182604405133134129118.8859'
    jDoc: '1724183397337473908664175.3725'
